### ISSUE TITLE
Too many points in multiple answers/multiple choice questions

### ISSUE THREAD

**Issue by Jimvy** [OpenWeek/interactive-syllabus#3]
Dans le chapitre 6 (accessible chez https://github.com/ALambot/java-syllabus-pages/blob/master/pages/CH6_tableaux/qcm.rst), il y a 15 questions mais plusieurs choix par questions. Du coup, sans avoir tout correct, il y a moyen d'avoir des 25/15 sans avoir répondu à tout et sans avoir nécessairement juste. Il faudra retravailler ça dans l'intégration INGInious (un point si toutes les bonnes réponses, ou alors un point par bonne réponse et du coup avoir un total qui est plus grand que le nombre de questions).

**Comment by AlexandreDubray** [comment]
Hello,

Merci pour la remarque. Cela a été fixer. Le nombre  de proposition est maintenant égale aux nombre de propositions correcte dans le QCM et le nombre de bonne réponses est le nombre de proposition correcte cochée.

**Comment by Jimvy** [comment]
Fixed by 6c28e322 ? Je confirme le bon fonctionnement.
